### ISSUE TITLE
webui crashes in presence of binary (non-UTF-8) log file

### ISSUE THREAD

**Issue by AloisMahdal** [rhinstaller/permian#16]
After a binary file is added to logs (using `IsolatedWorkflow.logData()` or `GroupedWorkflow.groupLogData()`), webui will crash.

A "crude" but easy way to reproduce would be--once #15 is merged--alter *tests/test_library/testing_plugin_8.tc.yaml* so that the `data_hex` key includes non-UTF-8 bytes.

      [..]
      [..]
    STARTING TEST: tests/integration/test_testing_plugin/test_7.sh
    Verifies execution of workflows with logs
    + test
    + PIPELINEPLUGINS_ENABLE=test
    + ./pipeline test -o library.defaultCaseConfigMergeMethod=extension -o library.directPath=tests/test_library -o testingPlugin.reportSenderDirectory=/tmp/tmp.9MAWMa5JRE -o workflows.local_logs_dir=/tmp/tmp.ivl9qzSPtC --tp 'testing plugin plan 9'
    INFO:libpermian.webui.callbacks(Thread-2):WebUI started at: http://10.0.2.100:50580/
    [2022-03-15 11:04:12,530] ERROR in app: Exception on /logs/af8351f1315424feb7ae8a2000d29a9d12f114e2/horse [GET]
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
        response = self.full_dispatch_request()
      File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/usr/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
        raise value
      File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/root/permian/libpermian/webui/builtin.py", line 61, in logs
        return Response(logfile.read(), mimetype="text/plain")
      File "/usr/lib64/python3.6/codecs.py", line 321, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
    [2022-03-15 11:04:12,555] ERROR in app: Exception on /logs/1bbc1c85a2c20554b2741590e766aa127ceb05c3/horse [GET]
      [..]
      [..]

(Above, I did it by replacing the key content with 1-pixel PNG, but I believe it should be enough to just replace any byte with 0x89, ie. `89` in the `data_hex` key.)

It seems that at some point, webui is trying to load *and decode* every logfile as UTF-8.  As @pholica explained to me, this is likely related to dumping of the UI for later access and in current production this would not prevent pipeline from submitting the results.  (It would still break access to the web UI dump..)

**Comment by AloisMahdal** [comment]
Note that it would be also possible to reproduce this prior to #15, with something like this

    crc = CaseRunConfiguration(..)
    with crc.openLogfile('workflow', 'wb', filename='workflow.txt') as fh:
        fh.write(bytes.fromhex('89'))

(I haven't tried it..)

**Comment by pholica** [comment]
I'm thinking how to approach this as there are 2 problems (`libpermian.webui.builtin.logs` - https://github.com/rhinstaller/permian/blob/main/libpermian/webui/builtin.py#L57):

- Opening and reading the file in correct mode binary vs text (utf-8 encoded)
- Providing correct mimetype (until now, everything in logs was utf-8 encoded text)

I'm thinking about possible solutions or their combination (but I'm not sure if all of them are valid/possible):

- Open all the files by the WebUI in binary mode
- Set mimetype text/plain only for logs with filename ending with .txt
- Use `flask.send_file` https://flask.palletsprojects.com/en/2.0.x/api/#flask.send_file and don't use `libpermian.caserunconfiguration.CaseRunConfiguration.openLogFile` at all - `libpermian.exceptions.RemoteLogError` cannot be used with this approach

**Comment by velezd** [comment]
This is fixed in #23
