### ISSUE TITLE
Empty 'x86_64' value of bootIso structure inference from url broken for Anaconda workflow

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/permian#27]
With the PR https://github.com/rhinstaller/permian/pull/24
one of our use cases from https://github.com/rhinstaller/kickstart-tests/blob/master/.github/workflows/scenarios-permian.yml (happens for rhel8 and rhel9 scenarios) was broken.
The case:
```
run_event '{"type":"github.scheduled.daily.kstest.rhel8",
"bootIso":{"x86_64":""},
"kstestParams":{"platform":"rhel8","urls":{"x86_64":{"installation_tree":"http://download.eng.bos.redhat.com/rhel-8/development/RHEL-8/latest-RHEL-8/compose/BaseOS/x86_64/os","modular_url":"http://download.eng.bos.redhat.com/rhel-8/development/RHEL-8/latest-RHEL-8/compose/AppStream/x86_64/os"}}}}'
```
The case(s) we would like to cover are defined in the test added in:
https://github.com/rvykydal/permian/commit/0e6ffc7b041ae17dac5e21bd0b3489863bf94cdd

I think the behaviour of the cases is worth face to face discussion.
Is it correct to supply bootIso with empty values for archs or missing archs ? It is easier for us given the way how we construct the event in the GitHub workflow, but maybe we should prohibit using empty value for an arch and do not supply the arch key in such case - that would still require some update of the code in the plugin as well.

For now we are using branch from my fork with revert of the PR for deployed daily workflow: https://github.com/rvykydal/permian/commits/kstest-revert-boot-iso-conversion

**Comment by velezd** [comment]
This is expected behavior. Since bootIso is defined, there is no attempt for conversion from kstestParams. You are basically overriding the bootIso with empty value and then want to ignore that override. This should be easy to fix using bash parameter expansion in your workflow. Or we could implement custom pipeline command that would make it easier for you to provide the parameters. For example of custom command you can check libpermian/plugins/compose/__init__.py

**Comment by rvykydal** [comment]
Ok, so I will change the workflow to add the bootIso structure only in case it is defined.
I am just adding a note here that using only conversion mechanism in the plugin would not allow defining bootIso for some architectures while using kstestsParams.url for others. But we can solve this case if/when it really becomes issue and add logic to handle it into the plugin.

**Comment by rvykydal** [comment]
> Ok, so I will change the GH workflow to add the bootIso structure only in case it is defined.
https://github.com/rhinstaller/kickstart-tests/pull/727

**Comment by velezd** [comment]
There is still the hypothetical issue of not being able to override boot iso for just one architecture. I talked about it with @pholica and some common solution on the level of event structures would be difficult. So I would say, let's worry about it when/if we actually need it.
